Repository gsp-eeg/EEGraSP, pull requests merged in 2024-07, with the labels that each got.

#63 56 fix eegrasp docstrings
  eegrasp/eegrasp.py
Labels: documentation

#94 91 badges are broken
  README.rst
Labels: documentation

#98 Fix example. Fit sigma does not input distances into compute_graph call.
  eegrasp/eegrasp.py
  examples/ERP_reconstruction.py
Labels: bug

#67 55 eegrasp should take an nme class as attribute
  eegrasp/eegrasp.py
  eegrasp/tests/load_from_mne.py
Labels: enhancement, basic functionality

#90 9 add a visualization method to generate an image with the graph and the head contour
  eegrasp/eegrasp.py
  eegrasp/viz.py
  examples/plot_eeg_graph.py
Labels: enhancement, basic functionality
